name: Shops
version: 1.0
main: net.sparkzz.shops.Shops
depend: [Vault]
author: MrSparkzz
description: Command/Location based shoping plugin.

commands:
  buy:
    description: Buy something from a store.
  sell:
    description: Sell something to a store.
  browse:
    description: Browse the current store.

permissions:
  shops.browse:
    default: true
    description: Allow a player to browse a shop.
  shops.buy:
    default: true
    description: Allow a player to buy from a shop.
  shops.sell:
    default: true
    description: Allow a player to sell to a shop.
  shops.*:
    default: op
    children:
      shops.browse: true
      shops.buy: true
      shops.sell: true